name: Deploy SQL Server Database

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SQLCMD
        run: sudo apt-get install -y mssql-tools unixodbc-dev

      - name: Deploy Database & Table
        run: |
          sqlcmd -S "tcp:0.tcp.pinggy.io,1433" -U Auto_user -P "SambePassword@1" -d master -i setup.sql
